# Generated by Django 5.2.1 on 2026-06-13 04:00
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        TrigramExtension()
    ]
