# Generated by Django 5.0.4 on 2025-09-19 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_slug_coments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coments',
            new_name='Comment',
        ),
        migrations.RenameIndex(
            model_name='comment',
            new_name='blog_commen_created_0e6ed4_idx',
            old_name='blog_coment_created_fdd37b_idx',
        ),
    ]
